import './globals.css'
import {Metadata} from "next";
import TheHeader from "@/app/components/TheHeader";
import TheFooter from "@/app/components/TheFooter";
import Style from './page.module.css'

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <TheHeader/>
        <main className={Style.main}>
            {children}
        </main>

        <TheFooter/>
        </body>

        </html>
    )
}
